### PR TITLE
Adds arrow2

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This PR is pending IP clearance. Do not merge until IP is cleared.

It contains the source code of arrow2 rebased on top of all commits in arrow-rs, so that history of arrow-rs is preserved.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
@abreis @elferherrera @ritchie46 @Jibbow @domoritz @Dandandan , for Apache's IP clearance:

* would it be ok for your contributions to arrow2 to be donated to Apache under [the CLA](https://www.apache.org/licenses/icla.pdf)?
* if yes, could you sign and submit a CLA, so that we have the paperwork in order for this to proceed?

Sorry for the inconvenience, this does not seem to be needed in normal contributions, but for some reason for these clearances it is required.

**Comment by domoritz** [comment]
I already signed an ICLA and yes, I am ok with donating my contributions to arrow2.

**Comment by andizimmerer** [comment]
Sure, I'm also fine with it. Just signed the ICLA and submitted it :)

**Comment by ritchie46** [comment]
~Will do!~

Have done!

**Comment by elferherrera** [comment]
These are great news. Glad to know it is moving to Apache. I signed and sent my copy

**Comment by Dandandan** [comment]
I fully support this to be donated!

**Comment by abreis** [comment]
I support this donation and I've sent a signed CLA.

Best of luck with the project!

**Pull request closed without merging**
